using BrawlLib.Internal;
using BrawlLib.SSBB.Types.Subspace.Triggers;
using System.Runtime.InteropServices;

namespace BrawlLib.SSBB.Types.Subspace.Objects
{
    [StructLayout(LayoutKind.Sequential, Pack = 1)]
    public struct GPS2Entry
    {
        public const int Size = 0x120;

        public bfloat _unknown0x000;
        public byte _unknown0x004;
        public byte _unknown0x005;
        public byte _unknown0x006;
        public byte _unknown0x007;
        public bfloat _unknown0x008;
        public byte _unknown0x00C;
        public byte _unknown0x00D;
        public byte _unknown0x00E;
        public byte _unknown0x00F;
        public buint _unknown0x010;
        public buint _unknown0x014;
        public buint _unknown0x018;
        public buint _unknown0x01C;
        public buint _unknown0x020;
        public buint _unknown0x024;
        public bfloat _unknown0x028;
        public buint _unknown0x02C;
        public buint _unknown0x030;
        public bfloat _unknown0x034;
        public buint _unknown0x038;
        public buint _unknown0x03C;
        public buint _unknown0x040;
        public bfloat _unknown0x044;
        public buint _unknown0x048;
        public buint _unknown0x04C;
        public buint _unknown0x050;
        public buint _unknown0x054;
        public buint _unknown0x058;
        public bshort _unknown0x05C;
        public bshort _unknown0x05E;
        public byte _unknown0x060;
        public byte _unknown0x061;
        public byte _unknown0x062;
        public byte _unknown0x063;
        public buint _unknown0x064;
        public buint _unknown0x068;
        public buint _unknown0x06C;
        public buint _unknown0x070;
        public byte _unknown0x074;
        public byte _unknown0x075;
        public byte _unknown0x076;
        public byte _unknown0x077;
        public buint _unknown0x078;
        public buint _unknown0x07C;
        public buint _unknown0x080;
        public buint _unknown0x084;
        public buint _unknown0x088;
        public buint _unknown0x08C;
        public buint _unknown0x090;
        public bfloat _unknown0x094;
        public bfloat _unknown0x098;
        public bfloat _unknown0x09C;
        public bfloat _unknown0x0A0;
        public bfloat _unknown0x0A4;
        public bfloat _unknown0x0A8;
        public bfloat _unknown0x0AC;
        public bfloat _unknown0x0B0;
        public bfloat _unknown0x0B4;
        public bfloat _unknown0x0B8;
        public bfloat _unknown0x0BC;
        public bfloat _unknown0x0C0;
        public bfloat _unknown0x0C4;
        public bfloat _unknown0x0C8;
        public bfloat _unknown0x0CC;
        public bfloat _unknown0x0D0;
        public bfloat _unknown0x0D4;
        public bfloat _unknown0x0D8;
        public bfloat _unknown0x0DC;
        public bfloat _unknown0x0E0;
        public bfloat _unknown0x0E4;
        public TriggerData _unknown0x0E8;
        public buint _unknown0x0EC;
        public buint _unknown0x0F0;
        public buint _unknown0x0F4;
        public byte _unknown0x0F8;
        public byte _unknown0x0F9;
        public byte _unknown0x0FA;
        public byte _unknown0x0FB;
        public byte _unknown0x0FC;
        public byte _unknown0x0FD;
        public byte _unknown0x0FE;
        public byte _unknown0x0FF;
        public byte _unknown0x100;
        public byte _unknown0x101;
        public byte _unknown0x102;
        public byte _unknown0x103;
        public byte _unknown0x104;
        public byte _unknown0x105;
        public byte _unknown0x106;
        public byte _unknown0x107;
        public buint _unknown0x108;
        public buint _unknown0x10C;
        public buint _unknown0x110;
        public buint _unknown0x114;
        public buint _unknown0x118;
        public TriggerData _unknown0x11C;
    }
}