//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BrawlCrate.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.3.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool UpdateSettings {
            get {
                return ((bool)(this["UpdateSettings"]));
            }
            set {
                this["UpdateSettings"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShowFullPath {
            get {
                return ((bool)(this["ShowFullPath"]));
            }
            set {
                this["ShowFullPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection RecentFiles {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["RecentFiles"]));
            }
            set {
                this["RecentFiles"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public int RecentFilesMax {
            get {
                return ((int)(this["RecentFilesMax"]));
            }
            set {
                this["RecentFilesMax"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool DisplayPropertyDescriptionWhenAvailable {
            get {
                return ((bool)(this["DisplayPropertyDescriptionWhenAvailable"]));
            }
            set {
                this["DisplayPropertyDescriptionWhenAvailable"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ShowHex {
            get {
                return ((bool)(this["ShowHex"]));
            }
            set {
                this["ShowHex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::BrawlLib.Internal.ModelEditorSettings ViewerSettings {
            get {
                return ((global::BrawlLib.Internal.ModelEditorSettings)(this["ViewerSettings"]));
            }
            set {
                this["ViewerSettings"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ViewerSettingsSet {
            get {
                return ((bool)(this["ViewerSettingsSet"]));
            }
            set {
                this["ViewerSettingsSet"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool PixelLighting {
            get {
                return ((bool)(this["PixelLighting"]));
            }
            set {
                this["PixelLighting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool APIEnabled {
            get {
                return ((bool)(this["APIEnabled"]));
            }
            set {
                this["APIEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string PythonInstallationPath {
            get {
                return ((string)(this["PythonInstallationPath"]));
            }
            set {
                this["PythonInstallationPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FSharpInstallationPath {
            get {
                return ((string)(this["FSharpInstallationPath"]));
            }
            set {
                this["FSharpInstallationPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool CheckUpdatesAtStartup {
            get {
                return ((bool)(this["CheckUpdatesAtStartup"]));
            }
            set {
                this["CheckUpdatesAtStartup"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool GetDocumentationUpdates {
            get {
                return ((bool)(this["GetDocumentationUpdates"]));
            }
            set {
                this["GetDocumentationUpdates"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool UpdateAutomatically {
            get {
                return ((bool)(this["UpdateAutomatically"]));
            }
            set {
                this["UpdateAutomatically"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool DiscordRPCEnabled {
            get {
                return ((bool)(this["DiscordRPCEnabled"]));
            }
            set {
                this["DiscordRPCEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Nullable<BrawlCrate.Discord.DiscordSettings.ModNameType> DiscordRPCNameType {
            get {
                return ((global::System.Nullable<BrawlCrate.Discord.DiscordSettings.ModNameType>)(this["DiscordRPCNameType"]));
            }
            set {
                this["DiscordRPCNameType"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("My Mod")]
        public string DiscordRPCNameCustom {
            get {
                return ((string)(this["DiscordRPCNameCustom"]));
            }
            set {
                this["DiscordRPCNameCustom"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool PreviewBRRESModels {
            get {
                return ((bool)(this["PreviewBRRESModels"]));
            }
            set {
                this["PreviewBRRESModels"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool PreviewARCModels {
            get {
                return ((bool)(this["PreviewARCModels"]));
            }
            set {
                this["PreviewARCModels"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string BuildPath {
            get {
                return ((string)(this["BuildPath"]));
            }
            set {
                this["BuildPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection APILoadersBlacklist {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["APILoadersBlacklist"]));
            }
            set {
                this["APILoadersBlacklist"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection APILoadersWhitelist {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["APILoadersWhitelist"]));
            }
            set {
                this["APILoadersWhitelist"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool APIOnlyAllowLoadersFromWhitelist {
            get {
                return ((bool)(this["APIOnlyAllowLoadersFromWhitelist"]));
            }
            set {
                this["APIOnlyAllowLoadersFromWhitelist"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool APIAutoUpdate {
            get {
                return ((bool)(this["APIAutoUpdate"]));
            }
            set {
                this["APIAutoUpdate"] = value;
            }
        }
    }
}
