//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BrawlLib.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BrawlLib.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        public static System.Drawing.Icon BrawlCrateCanaryIcon {
            get {
                object obj = ResourceManager.GetObject("BrawlCrateCanaryIcon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        public static System.Drawing.Icon BrawlCrateGoldCanaryIcon {
            get {
                object obj = ResourceManager.GetObject("BrawlCrateGoldCanaryIcon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        public static System.Drawing.Icon BrawlCrateGoldIcon {
            get {
                object obj = ResourceManager.GetObject("BrawlCrateGoldIcon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        public static System.Drawing.Icon BrawlCrateIcon {
            get {
                object obj = ResourceManager.GetObject("BrawlCrateIcon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        public static System.Drawing.Icon BrawlCratePresentIcon {
            get {
                object obj = ResourceManager.GetObject("BrawlCratePresentIcon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basic.
        /// </summary>
        public static string Collision0x00 {
            get {
                return ResourceManager.GetString("Collision0x00", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rock.
        /// </summary>
        public static string Collision0x01 {
            get {
                return ResourceManager.GetString("Collision0x01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grass.
        /// </summary>
        public static string Collision0x02 {
            get {
                return ResourceManager.GetString("Collision0x02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Soil.
        /// </summary>
        public static string Collision0x03 {
            get {
                return ResourceManager.GetString("Collision0x03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wood.
        /// </summary>
        public static string Collision0x04 {
            get {
                return ResourceManager.GetString("Collision0x04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light Metal.
        /// </summary>
        public static string Collision0x05 {
            get {
                return ResourceManager.GetString("Collision0x05", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heavy Metal.
        /// </summary>
        public static string Collision0x06 {
            get {
                return ResourceManager.GetString("Collision0x06", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Carpet.
        /// </summary>
        public static string Collision0x07 {
            get {
                return ResourceManager.GetString("Collision0x07", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alien.
        /// </summary>
        public static string Collision0x08 {
            get {
                return ResourceManager.GetString("Collision0x08", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bulborb.
        /// </summary>
        public static string Collision0x09 {
            get {
                return ResourceManager.GetString("Collision0x09", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Water.
        /// </summary>
        public static string Collision0x0A {
            get {
                return ResourceManager.GetString("Collision0x0A", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rubber.
        /// </summary>
        public static string Collision0x0B {
            get {
                return ResourceManager.GetString("Collision0x0B", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slippery.
        /// </summary>
        public static string Collision0x0C {
            get {
                return ResourceManager.GetString("Collision0x0C", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Snow.
        /// </summary>
        public static string Collision0x0D {
            get {
                return ResourceManager.GetString("Collision0x0D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Icy Snow.
        /// </summary>
        public static string Collision0x0E {
            get {
                return ResourceManager.GetString("Collision0x0E", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game &amp; Watch.
        /// </summary>
        public static string Collision0x0F {
            get {
                return ResourceManager.GetString("Collision0x0F", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subspace Ice.
        /// </summary>
        public static string Collision0x10 {
            get {
                return ResourceManager.GetString("Collision0x10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checkered.
        /// </summary>
        public static string Collision0x11 {
            get {
                return ResourceManager.GetString("Collision0x11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spike Hazard (Target Test Only).
        /// </summary>
        public static string Collision0x12 {
            get {
                return ResourceManager.GetString("Collision0x12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hazard 2 (Subspace Only).
        /// </summary>
        public static string Collision0x13 {
            get {
                return ResourceManager.GetString("Collision0x13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hazard 3 (Subspace Only).
        /// </summary>
        public static string Collision0x14 {
            get {
                return ResourceManager.GetString("Collision0x14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Electroplankton.
        /// </summary>
        public static string Collision0x15 {
            get {
                return ResourceManager.GetString("Collision0x15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cloud.
        /// </summary>
        public static string Collision0x16 {
            get {
                return ResourceManager.GetString("Collision0x16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subspace.
        /// </summary>
        public static string Collision0x17 {
            get {
                return ResourceManager.GetString("Collision0x17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stone Bricks.
        /// </summary>
        public static string Collision0x18 {
            get {
                return ResourceManager.GetString("Collision0x18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dustless.
        /// </summary>
        public static string Collision0x19 {
            get {
                return ResourceManager.GetString("Collision0x19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mario Bros..
        /// </summary>
        public static string Collision0x1A {
            get {
                return ResourceManager.GetString("Collision0x1A", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grate.
        /// </summary>
        public static string Collision0x1B {
            get {
                return ResourceManager.GetString("Collision0x1B", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sand.
        /// </summary>
        public static string Collision0x1C {
            get {
                return ResourceManager.GetString("Collision0x1C", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home-Run Contest.
        /// </summary>
        public static string Collision0x1D {
            get {
                return ResourceManager.GetString("Collision0x1D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Water (No Splash).
        /// </summary>
        public static string Collision0x1E {
            get {
                return ResourceManager.GetString("Collision0x1E", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown 0x1F.
        /// </summary>
        public static string Collision0x1F {
            get {
                return ResourceManager.GetString("Collision0x1F", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CollEx.
        /// </summary>
        public static string CollisionExpansion {
            get {
                return ResourceManager.GetString("CollisionExpansion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ceiling.
        /// </summary>
        public static string CollisionTypeCeiling {
            get {
                return ResourceManager.GetString("CollisionTypeCeiling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Floor.
        /// </summary>
        public static string CollisionTypeFloor {
            get {
                return ResourceManager.GetString("CollisionTypeFloor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left Wall.
        /// </summary>
        public static string CollisionTypeLeftWall {
            get {
                return ResourceManager.GetString("CollisionTypeLeftWall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        public static string CollisionTypeNone {
            get {
                return ResourceManager.GetString("CollisionTypeNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right Wall.
        /// </summary>
        public static string CollisionTypeRightWall {
            get {
                return ResourceManager.GetString("CollisionTypeRightWall", resourceCulture);
            }
        }

        /// <summary>
        ///   Gets the current icon to be used by the program
        /// </summary>
        public static System.Drawing.Icon Icon {
            get {
                if (BrawlLib.BrawlCrate.PerSessionSettings.ProgramBirthday)
                {
                    return PartyBallIcon;
                }
                if (BrawlLib.BrawlCrate.PerSessionSettings.BrawlCrateBirthday)
                {
                    return BrawlCratePresentIcon;
                }
#if CANARY
                return BrawlLib.BrawlCrate.PerSessionSettings.IsBrawlCrateGold ? BrawlCrateGoldCanaryIcon : BrawlCrateCanaryIcon;
#else
                return BrawlLib.BrawlCrate.PerSessionSettings.IsBrawlCrateGold ? BrawlCrateGoldIcon : BrawlCrateIcon;
#endif
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        public static System.Drawing.Icon PartyBallIcon {
            get {
                object obj = ResourceManager.GetObject("PartyBallIcon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
    }
}
